In [35]:
import numpy as np
import scipy
import scipy.linalg  

### Задача 1

In [4]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

### Задача 2

x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15


In [6]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2],[2, 0, -5], [11, 4, -7]])

In [7]:
B = np.array([1, 7, 12, 7, 15])

In [8]:
np.linalg.lstsq(A, B)

C:\Program Files\Python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

### Задача 3

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

0.0

Определим определитель матрицы А

In [12]:
np.linalg.det(A)

0.0

Определитель равен 0, следовательно СЛАУ решения не имеет. Приведем систему к однородному виду

In [21]:
B = np.array([0, 0, 0])

In [22]:
np.linalg.lstsq(A, B)

C:\Program Files\Python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([0., 0., 0.]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

### Задача 4

In [36]:
A = np.array([[1, 2, 3], [2, 26, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [ 0.25       -0.41666667  1.        ]]
[[  4.          28.          73.        ]
 [  0.          12.         -15.5       ]
 [  0.           0.         -21.70833333]]


In [38]:
B = np.array([4, 1, 7])
np.linalg.solve(A, B)

array([ 4.72744722, -0.28023033, -0.05566219])

### Задача 5

x+2y−z=1 
8x−5y+2z=12

In [23]:
a = np.array([[1, 2, -1], [8, -5, 2]])
b = np.array([1, 12])

In [24]:
np.linalg.lstsq(A, B)

C:\Program Files\Python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([0., 0., 0.]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))

### Задача 6

In [25]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

In [26]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [27]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  3.55271368e-15])

In [28]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.92767275e-15])

In [29]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 3.92767275e-15 0.00000000e+00]


1.499999999999996

In [30]:
np.linalg.norm(np.dot(A, X) - B)

1.224744871391589

In [31]:
X = np.array([1.5, 1, 0.5])
np.linalg.norm(X),  np.linalg.norm(np.dot(A, X) - B)   

(1.8708286933869707, 15.297058540778355)